apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argo-cd
spec:
  destination:
    namespace: n8n
    server: https://kubernetes.default.svc
  project: n8n
  source:
    chart: n8n
    repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.5.10
    helm:
      valuesObject:
        extraEnvVars:
          N8N_SECURE_COOKIE: "false"
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
          hosts:
            - host: n8n.localhost
              paths:
                - path: /
                  pathType: Prefix
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 