apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: traefik
  namespace: argo-cd
spec:
  description: Projet ArgoCD pour la gestion de Traefik
  sourceRepos:
    - '*'
  destinations:
    - namespace: traefik
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*' 