apiVersion: v1
kind: Secret
metadata:
  name: repo-traefik
  namespace: argo-cd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: repo-traefik
  project: traefik
  type: helm
  url: https://traefik.github.io/charts
type: Opaque 